config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
  <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <!--<a class="navbar-brand" href="index.html">Start Bootstrap</a>-->
        <%=link_to "hou", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <!--<a class="nav-link" href="index.html">Home</a>-->
              <%=link_to "Home", root_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <!--<a class="nav-link" href="about.html">About</a>-->
               <%=link_to "New Post", new_post_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <!--<a class="nav-link" href="post.html">Sample Post</a>-->
                <%if user_signed_in? %>
                    <%=link_to "Logout", destroy_user_session_path, method: :delete, data: {confirm: "로그아웃 하시겠습니까?"}, class: "nav-link"%>
                <%else%>
                    <%=link_to "Login", new_user_session_path, class: "nav-link"%>
                <% end %>
            </li>
            <!--<li class="nav-item">-->
            <!--  <a class="nav-link" href="contact.html">Contact</a>-->
            <!--</li>-->
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <!--resizing-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%=render '/layouts/nav' %>
<%= yield %>
<%=render '/layouts/footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url(<%= asset_path 'contact-bg.jpg' %>)">
 <div class="overlay"></div>
 <div class="container">
   <div class="row">
     <div class="col-lg-8 col-md-10 mx-auto">
       <div class="page-heading">
         <h1>New Post</h1>
         <span class="subheading">Create a new post</span>
       </div>
     </div>
   </div>
 </div>
</header>

<!-- Main Content -->
<div class="container">
 <div class="row">
   <div class="col-lg-8 col-md-10 mx-auto">
     <%= form_tag "", id: "contactForm", novalidate: true do %>
       <div class="control-group">
         <div class="form-group floating-label-form-group controls">
           <label>Title</label>
           <%= text_field_tag "post[title]", "",class: "form-control", placeholder: "Title" %>
         </div>
       </div>
       <div class="control-group">
         <div class="form-group floating-label-form-group controls">
           <label>Contents</label>
           <%= text_area_tag "post[contents]", "",class: "form-control", placeholder: "Contents" %>
           <p class="help-block text-danger"></p>
         </div>
       </div>
       <br>
       <div id="success"></div>
       <div class="form-group">
         <button type="submit" class="btn btn-primary" id="sendMessageButton">글올리기</button>
       </div>
     <% end %>
   </div>
 </div>
</div>

   <hr>




<%= form_for(@post) do |f| %>
 <% if @post.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

     <ul>
     <% @post.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
   <%= f.label :title %><br>
   <%= f.text_field :title %>
 </div>
 <div class="field">
   <%= f.label :contents %><br>
   <%= f.text_area :contents %>
 </div>
 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url(<%= asset_path 'home-bg.jpg'%>)">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>hou</h1>
          <span class="subheading">useful Bookmark</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto" id="posts_index">
        <% @posts.each do |post| %>
        <div class="post-preview">
            <a href="<%=post_path(post)%>">
              <h2 class="post-title">
                <%= post.title%>
                Man must explore, and this is exploration at its greatest
              </h2>
              <h3 class="post-subtitle">
               <%= truncate post.contents, length: 50%>
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="<%=post_path(post)%>">Start Bootstrap</a>
              on <%=post.created_at.to_s(:long) %></p>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1><%= @post.title %></h1>
          <h2 class="subheading">A Blog Theme by Start Bootstrap</h2>
          <span class="meta">Posted by
            <a href="#">Start Bootstrap</a>
            <%= @post.created_at.to_s(:long) %></span>

        </div>
      </div>
    </div>
  </div>
</header>


  <!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h2 class="section-heading">The Final Frontier</h2>
        <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
        
        <%= @post.contents %>

        <a href="#">
          <img class="img-fluid" src="<%=asset_path 'post-bg.jpg'%>" alt="">
        </a>
        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>

          <p>Placeholder text by
          <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by
          <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p>
      </div>
    </div>
  </div>
</article>

    <hr>